401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
5
FuncDecl(Id(foo)[VarDecl(Id(a)),VarDecl(Id(b)),VarDecl(Id(c)),VarDecl(Id(d)),VarDecl(Id(e))],([VarDecl(Id(z))][Assign(Id(a),IntLiteral(4)),Assign(Id(b),IntLiteral(21)),Assign(Id(c),IntLiteral(6)),Assign(Id(d),StringLiteral(Hello)),Assign(Id(z),UnaryOp(!,Id(e))),Assign(Id(a),BinaryOp(&&,BinaryOp(==,Id(b),Id(c)),UnaryOp(!,Id(d))))]))
492
493
494
495
496
1
FuncDecl(Id(foo)[VarDecl(Id(x))],([][Assign(Id(x),IntLiteral(2))]))
497
498
499
500
489
Tests run  101
Errors  [(<CheckSuite.CheckSuite testMethod=test_453>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 751, in test_453\n    self.assertTrue(TestChecker.test(input,expect,453))\n  File "./test/TestUtils.py", line 128, in test\n    return TestChecker.checkStatic(input,expect,num)\n  File "./test/TestUtils.py", line 139, in checkStatic\n    asttree = ASTGeneration().visit(tree)\n  File "/home/nguyendat/.local/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit\n    return tree.accept(self)\n  File "../target/main/bkit/parser/BKITParser.py", line 429, in accept\n    return visitor.visitProgram(self)\n  File "./main/bkit/astgen/ASTGeneration.py", line 12, in visitProgram\n    funcs_decls = list(reduce(lambda y,x: y + [self.visitFunction_declare(x)], [item for item in ctx.function_declare()], []))\n  File "./main/bkit/astgen/ASTGeneration.py", line 12, in <lambda>\n    funcs_decls = list(reduce(lambda y,x: y + [self.visitFunction_declare(x)], [item for item in ctx.function_declare()], []))\n  File "./main/bkit/astgen/ASTGeneration.py", line 21, in visitFunction_declare\n    stmt = list(reduce(lambda y, x: y + [self.visitStmt(x)], ctx.stmt(), []))\n  File "./main/bkit/astgen/ASTGeneration.py", line 21, in <lambda>\n    stmt = list(reduce(lambda y, x: y + [self.visitStmt(x)], ctx.stmt(), []))\n  File "./main/bkit/astgen/ASTGeneration.py", line 88, in visitStmt\n    return self.visitAssign_stmt(ctx.assign_stmt())\n  File "./main/bkit/astgen/ASTGeneration.py", line 141, in visitAssign_stmt\n    lhs = Id(ctx.ID().getText()) if ctx.ID() else self.visit( ctx.array_cell())\n  File "/home/nguyendat/.local/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit\n    return tree.accept(self)\n  File "../target/main/bkit/parser/BKITParser.py", line 2102, in accept\n    return visitor.visitArray_cell(self)\n  File "./main/bkit/astgen/ASTGeneration.py", line 147, in visitArray_cell\n    arr = self.visitExpr7(ctx.expr7())\n  File "./main/bkit/astgen/ASTGeneration.py", line 227, in visitExpr7\n    return self.visitExpr8(ctx.expr8())\n  File "./main/bkit/astgen/ASTGeneration.py", line 234, in visitExpr8\n    return self.visitExpr(ctx.expr())\n  File "./main/bkit/astgen/ASTGeneration.py", line 176, in visitExpr\n    return self.visitExpr1(ctx.expr1(0))\n  File "./main/bkit/astgen/ASTGeneration.py", line 181, in visitExpr1\n    if ctx.getChildCount() > 2:\nAttributeError: \'NoneType\' object has no attribute \'getChildCount\'\n'), (<CheckSuite.CheckSuite testMethod=test_case_90>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 1539, in test_case_90\n    self.assertTrue(TestChecker.test(input, expect, 489))\n  File "./test/TestUtils.py", line 128, in test\n    return TestChecker.checkStatic(input,expect,num)\n  File "./test/TestUtils.py", line 147, in checkStatic\n    res = checker.check()\n  File "./main/bkit/checker/StaticCheck.py", line 67, in check\n    return self.visit(self.ast,self.global_envi)\n  File "./main/bkit/utils/Visitor.py", line 7, in visit\n    return ast.accept(self,param)\n  File "./main/bkit/utils/AST.py", line 55, in accept\n    return v.visitProgram(self, param)\n  File "./main/bkit/checker/StaticCheck.py", line 83, in visitProgram\n    [self.visit(x,self.env) for x in ast.decl]\n  File "./main/bkit/checker/StaticCheck.py", line 83, in <listcomp>\n    [self.visit(x,self.env) for x in ast.decl]\n  File "./main/bkit/utils/Visitor.py", line 7, in visit\n    return ast.accept(self,param)\n  File "./main/bkit/utils/AST.py", line 84, in accept\n    return v.visitFuncDecl(self, param)\n  File "./main/bkit/checker/StaticCheck.py", line 155, in visitFuncDecl\n    res_type_list += [self.visit(stmt, cur_env)]\n  File "./main/bkit/utils/Visitor.py", line 7, in visit\n    return ast.accept(self,param)\n  File "./main/bkit/utils/AST.py", line 267, in accept\n    return v.visitDowhile(self, param)\n  File "./main/bkit/checker/StaticCheck.py", line 837, in visitDowhile\n    res_list = [self.visit(x, cur_env) for x in ast.sl[1]]\n  File "./main/bkit/checker/StaticCheck.py", line 837, in <listcomp>\n    res_list = [self.visit(x, cur_env) for x in ast.sl[1]]\n  File "./main/bkit/utils/Visitor.py", line 7, in visit\n    return ast.accept(self,param)\n  File "./main/bkit/utils/AST.py", line 290, in accept\n    return v.visitCallStmt(self, param)\n  File "./main/bkit/checker/StaticCheck.py", line 928, in visitCallStmt\n    if isinstance(func.mtype.intype[idx].mtype, (Unknown, Prim)):\nAttributeError: \'StringType\' object has no attribute \'mtype\'\n')]
[(<CheckSuite.CheckSuite testMethod=test_420>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 256, in test_420\n'
  '    self.assertTrue(TestChecker.test(input,expect,420))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_422>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 284, in test_422\n'
  '    self.assertTrue(TestChecker.test(input,expect,422))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_434>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 453, in test_434\n'
  '    self.assertTrue(TestChecker.test(input,expect,434))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_437>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 504, in test_437\n'
  '    self.assertTrue(TestChecker.test(input,expect,437))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_440>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 550, in test_440\n'
  '    self.assertTrue(TestChecker.test(input,expect,440))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_442>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 587, in test_442\n'
  '    self.assertTrue(TestChecker.test(input,expect,442))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_446>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 654, in test_446\n'
  '    self.assertTrue(TestChecker.test(input,expect,446))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_447>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 668, in test_447\n'
  '    self.assertTrue(TestChecker.test(input,expect,447))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_454>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 767, in test_454\n'
  '    self.assertTrue(TestChecker.test(input,expect,454))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_455>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 782, in test_455\n'
  '    self.assertTrue(TestChecker.test(input,expect,455))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_456>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 798, in test_456\n'
  '    self.assertTrue(TestChecker.test(input,expect,456))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_457>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 814, in test_457\n'
  '    self.assertTrue(TestChecker.test(input,expect,457))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_458>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 833, in test_458\n'
  '    self.assertTrue(TestChecker.test(input,expect,458))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_459>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 846, in test_459\n'
  '    self.assertTrue(TestChecker.test(input,expect,459))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_465>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 948, in test_465\n'
  '    self.assertTrue(TestChecker.test(input,expect,465))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_467>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 979, in test_467\n'
  '    self.assertTrue(TestChecker.test(input,expect,467))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_479>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1166, in test_479\n'
  '    self.assertTrue(TestChecker.test(input,expect,479))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_481>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1204, in test_481\n'
  '    self.assertTrue(TestChecker.test(input,expect,481))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_482>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1216, in test_482\n'
  '    self.assertTrue(TestChecker.test(input,expect,482))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_485>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1267, in test_485\n'
  '    self.assertTrue(TestChecker.test(input,expect,485))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_486>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1284, in test_486\n'
  '    self.assertTrue(TestChecker.test(input,expect,486))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_488>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1319, in test_488\n'
  '    self.assertTrue(TestChecker.test(input,expect,488))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_490>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1348, in test_490\n'
  '    self.assertTrue(TestChecker.test(input,expect,490))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_495>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 1444, in test_495\n'
  '    self.assertTrue(TestChecker.test(input,expect,495))\n'
  'AssertionError: False is not true\n')]
Test output
 ...................F.F...........F..F..F.F...FF.....EFFFFFF.....F.F...........F.FF..FF.F.F....F.....E
======================================================================
ERROR: test_453 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 751, in test_453
    self.assertTrue(TestChecker.test(input,expect,453))
  File "./test/TestUtils.py", line 128, in test
    return TestChecker.checkStatic(input,expect,num)
  File "./test/TestUtils.py", line 139, in checkStatic
    asttree = ASTGeneration().visit(tree)
  File "/home/nguyendat/.local/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "../target/main/bkit/parser/BKITParser.py", line 429, in accept
    return visitor.visitProgram(self)
  File "./main/bkit/astgen/ASTGeneration.py", line 12, in visitProgram
    funcs_decls = list(reduce(lambda y,x: y + [self.visitFunction_declare(x)], [item for item in ctx.function_declare()], []))
  File "./main/bkit/astgen/ASTGeneration.py", line 12, in <lambda>
    funcs_decls = list(reduce(lambda y,x: y + [self.visitFunction_declare(x)], [item for item in ctx.function_declare()], []))
  File "./main/bkit/astgen/ASTGeneration.py", line 21, in visitFunction_declare
    stmt = list(reduce(lambda y, x: y + [self.visitStmt(x)], ctx.stmt(), []))
  File "./main/bkit/astgen/ASTGeneration.py", line 21, in <lambda>
    stmt = list(reduce(lambda y, x: y + [self.visitStmt(x)], ctx.stmt(), []))
  File "./main/bkit/astgen/ASTGeneration.py", line 88, in visitStmt
    return self.visitAssign_stmt(ctx.assign_stmt())
  File "./main/bkit/astgen/ASTGeneration.py", line 141, in visitAssign_stmt
    lhs = Id(ctx.ID().getText()) if ctx.ID() else self.visit( ctx.array_cell())
  File "/home/nguyendat/.local/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "../target/main/bkit/parser/BKITParser.py", line 2102, in accept
    return visitor.visitArray_cell(self)
  File "./main/bkit/astgen/ASTGeneration.py", line 147, in visitArray_cell
    arr = self.visitExpr7(ctx.expr7())
  File "./main/bkit/astgen/ASTGeneration.py", line 227, in visitExpr7
    return self.visitExpr8(ctx.expr8())
  File "./main/bkit/astgen/ASTGeneration.py", line 234, in visitExpr8
    return self.visitExpr(ctx.expr())
  File "./main/bkit/astgen/ASTGeneration.py", line 176, in visitExpr
    return self.visitExpr1(ctx.expr1(0))
  File "./main/bkit/astgen/ASTGeneration.py", line 181, in visitExpr1
    if ctx.getChildCount() > 2:
AttributeError: 'NoneType' object has no attribute 'getChildCount'

======================================================================
ERROR: test_case_90 (CheckSuite.CheckSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1539, in test_case_90
    self.assertTrue(TestChecker.test(input, expect, 489))
  File "./test/TestUtils.py", line 128, in test
    return TestChecker.checkStatic(input,expect,num)
  File "./test/TestUtils.py", line 147, in checkStatic
    res = checker.check()
  File "./main/bkit/checker/StaticCheck.py", line 67, in check
    return self.visit(self.ast,self.global_envi)
  File "./main/bkit/utils/Visitor.py", line 7, in visit
    return ast.accept(self,param)
  File "./main/bkit/utils/AST.py", line 55, in accept
    return v.visitProgram(self, param)
  File "./main/bkit/checker/StaticCheck.py", line 83, in visitProgram
    [self.visit(x,self.env) for x in ast.decl]
  File "./main/bkit/checker/StaticCheck.py", line 83, in <listcomp>
    [self.visit(x,self.env) for x in ast.decl]
  File "./main/bkit/utils/Visitor.py", line 7, in visit
    return ast.accept(self,param)
  File "./main/bkit/utils/AST.py", line 84, in accept
    return v.visitFuncDecl(self, param)
  File "./main/bkit/checker/StaticCheck.py", line 155, in visitFuncDecl
    res_type_list += [self.visit(stmt, cur_env)]
  File "./main/bkit/utils/Visitor.py", line 7, in visit
    return ast.accept(self,param)
  File "./main/bkit/utils/AST.py", line 267, in accept
    return v.visitDowhile(self, param)
  File "./main/bkit/checker/StaticCheck.py", line 837, in visitDowhile
    res_list = [self.visit(x, cur_env) for x in ast.sl[1]]
  File "./main/bkit/checker/StaticCheck.py", line 837, in <listcomp>
    res_list = [self.visit(x, cur_env) for x in ast.sl[1]]
  File "./main/bkit/utils/Visitor.py", line 7, in visit
    return ast.accept(self,param)
  File "./main/bkit/utils/AST.py", line 290, in accept
    return v.visitCallStmt(self, param)
  File "./main/bkit/checker/StaticCheck.py", line 928, in visitCallStmt
    if isinstance(func.mtype.intype[idx].mtype, (Unknown, Prim)):
AttributeError: 'StringType' object has no attribute 'mtype'

======================================================================
FAIL: test_420 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 256, in test_420
    self.assertTrue(TestChecker.test(input,expect,420))
AssertionError: False is not true

======================================================================
FAIL: test_422 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 284, in test_422
    self.assertTrue(TestChecker.test(input,expect,422))
AssertionError: False is not true

======================================================================
FAIL: test_434 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 453, in test_434
    self.assertTrue(TestChecker.test(input,expect,434))
AssertionError: False is not true

======================================================================
FAIL: test_437 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 504, in test_437
    self.assertTrue(TestChecker.test(input,expect,437))
AssertionError: False is not true

======================================================================
FAIL: test_440 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 550, in test_440
    self.assertTrue(TestChecker.test(input,expect,440))
AssertionError: False is not true

======================================================================
FAIL: test_442 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 587, in test_442
    self.assertTrue(TestChecker.test(input,expect,442))
AssertionError: False is not true

======================================================================
FAIL: test_446 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 654, in test_446
    self.assertTrue(TestChecker.test(input,expect,446))
AssertionError: False is not true

======================================================================
FAIL: test_447 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 668, in test_447
    self.assertTrue(TestChecker.test(input,expect,447))
AssertionError: False is not true

======================================================================
FAIL: test_454 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 767, in test_454
    self.assertTrue(TestChecker.test(input,expect,454))
AssertionError: False is not true

======================================================================
FAIL: test_455 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 782, in test_455
    self.assertTrue(TestChecker.test(input,expect,455))
AssertionError: False is not true

======================================================================
FAIL: test_456 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 798, in test_456
    self.assertTrue(TestChecker.test(input,expect,456))
AssertionError: False is not true

======================================================================
FAIL: test_457 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 814, in test_457
    self.assertTrue(TestChecker.test(input,expect,457))
AssertionError: False is not true

======================================================================
FAIL: test_458 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 833, in test_458
    self.assertTrue(TestChecker.test(input,expect,458))
AssertionError: False is not true

======================================================================
FAIL: test_459 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 846, in test_459
    self.assertTrue(TestChecker.test(input,expect,459))
AssertionError: False is not true

======================================================================
FAIL: test_465 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 948, in test_465
    self.assertTrue(TestChecker.test(input,expect,465))
AssertionError: False is not true

======================================================================
FAIL: test_467 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 979, in test_467
    self.assertTrue(TestChecker.test(input,expect,467))
AssertionError: False is not true

======================================================================
FAIL: test_479 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1166, in test_479
    self.assertTrue(TestChecker.test(input,expect,479))
AssertionError: False is not true

======================================================================
FAIL: test_481 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1204, in test_481
    self.assertTrue(TestChecker.test(input,expect,481))
AssertionError: False is not true

======================================================================
FAIL: test_482 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1216, in test_482
    self.assertTrue(TestChecker.test(input,expect,482))
AssertionError: False is not true

======================================================================
FAIL: test_485 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1267, in test_485
    self.assertTrue(TestChecker.test(input,expect,485))
AssertionError: False is not true

======================================================================
FAIL: test_486 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1284, in test_486
    self.assertTrue(TestChecker.test(input,expect,486))
AssertionError: False is not true

======================================================================
FAIL: test_488 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1319, in test_488
    self.assertTrue(TestChecker.test(input,expect,488))
AssertionError: False is not true

======================================================================
FAIL: test_490 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1348, in test_490
    self.assertTrue(TestChecker.test(input,expect,490))
AssertionError: False is not true

======================================================================
FAIL: test_495 (CheckSuite.CheckSuite)
Created automatically
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 1444, in test_495
    self.assertTrue(TestChecker.test(input,expect,495))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 101 tests in 2.195s

FAILED (failures=24, errors=2)

