<<<<<<< HEAD
426
427
2
FuncDecl(Id(foo)[VarDecl(Id(x)),VarDecl(Id(y))],([][Assign(Id(x),BinaryOp(+,IntLiteral(1),IntLiteral(2))),Return(IntLiteral(1))]))
428
402
404
401
405
411
421
422
1
FuncDecl(Id(foo)[VarDecl(Id(x))],([][Assign(Id(x),BinaryOp(+,IntLiteral(1),IntLiteral(2))),Return(IntLiteral(1))]))
423
2
FuncDecl(Id(foo)[VarDecl(Id(x)),VarDecl(Id(a),[])],([][Assign(Id(x),BinaryOp(+,IntLiteral(1),IntLiteral(2))),Return(IntLiteral(1))]))
424
2
FuncDecl(Id(foo)[VarDecl(Id(x)),VarDecl(Id(a),[])],([][Assign(Id(x),BinaryOp(+,IntLiteral(1),IntLiteral(2))),Return(IntLiteral(1))]))
413
414
415
416
417
418
419
420
406
407
408
409
410
412
429
425
400
403
Tests run  30
Errors  []
[(<CheckSuite.CheckSuite testMethod=test_call_expr>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 378, in test_call_expr\n'
  '    self.assertTrue(TestChecker.test(input,expect,426))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_call_expr_1>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 397, in test_call_expr_1\n'
  '    self.assertTrue(TestChecker.test(input,expect,427))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_call_expr_2>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 418, in test_call_expr_2\n'
  '    self.assertTrue(TestChecker.test(input,expect,428))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_diff_numofparam_expr>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 34, in test_diff_numofparam_expr\n'
  '    self.assertTrue(TestChecker.test(input,expect,402))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_diff_numofparam_expr_use_ast>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 51, in '
  'test_diff_numofparam_expr_use_ast\n'
  '    self.assertTrue(TestChecker.test(input,expect,404))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 123, in test_func_decl\n'
  '    self.assertTrue(TestChecker.test(input,expect,411))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_10>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 283, in test_func_decl_10\n'
  '    self.assertTrue(TestChecker.test(input,expect,421))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_11>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 302, in test_func_decl_11\n'
  '    self.assertTrue(TestChecker.test(input,expect,422))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_12>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 321, in test_func_decl_12\n'
  '    self.assertTrue(TestChecker.test(input,expect,423))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_13>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 340, in test_func_decl_13\n'
  '    self.assertTrue(TestChecker.test(input,expect,424))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_2>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 142, in test_func_decl_2\n'
  '    self.assertTrue(TestChecker.test(input,expect,413))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_3>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 156, in test_func_decl_3\n'
  '    self.assertTrue(TestChecker.test(input,expect,414))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_4>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 172, in test_func_decl_4\n'
  '    self.assertTrue(TestChecker.test(input,expect,415))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_5>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 191, in test_func_decl_5\n'
  '    self.assertTrue(TestChecker.test(input,expect,416))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_6>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 210, in test_func_decl_6\n'
  '    self.assertTrue(TestChecker.test(input,expect,417))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_7>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 228, in test_func_decl_7\n'
  '    self.assertTrue(TestChecker.test(input,expect,418))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_8>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 246, in test_func_decl_8\n'
  '    self.assertTrue(TestChecker.test(input,expect,419))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_9>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 264, in test_func_decl_9\n'
  '    self.assertTrue(TestChecker.test(input,expect,420))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_1>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 69, in test_init_1\n'
  '    self.assertTrue(TestChecker.test(input,expect,406))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_3>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 89, in test_init_3\n'
  '    self.assertTrue(TestChecker.test(input,expect,408))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_4>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 99, in test_init_4\n'
  '    self.assertTrue(TestChecker.test(input,expect,409))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_5>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 109, in test_init_5\n'
  '    self.assertTrue(TestChecker.test(input,expect,410))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_no_entry_point>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 132, in test_no_entry_point\n'
  '    self.assertTrue(TestChecker.test(input,expect,412))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_redecl_global>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 440, in test_redecl_global\n'
  '    self.assertTrue(TestChecker.test(input,expect,429))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_undecl_var>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 359, in test_undecl_var\n'
  '    self.assertTrue(TestChecker.test(input,expect,425))\n'
  'AssertionError: False is not true\n')]
Test output
 FFFFF..FFFFFFFFFFFFFF.FFFFFF..
======================================================================
FAIL: test_call_expr (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 378, in test_call_expr
    self.assertTrue(TestChecker.test(input,expect,426))
AssertionError: False is not true

======================================================================
FAIL: test_call_expr_1 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 397, in test_call_expr_1
    self.assertTrue(TestChecker.test(input,expect,427))
AssertionError: False is not true

======================================================================
FAIL: test_call_expr_2 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 418, in test_call_expr_2
    self.assertTrue(TestChecker.test(input,expect,428))
AssertionError: False is not true

======================================================================
FAIL: test_diff_numofparam_expr (CheckSuite.CheckSuite)
More complex program
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 34, in test_diff_numofparam_expr
    self.assertTrue(TestChecker.test(input,expect,402))
AssertionError: False is not true

======================================================================
FAIL: test_diff_numofparam_expr_use_ast (CheckSuite.CheckSuite)
More complex program
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 51, in test_diff_numofparam_expr_use_ast
    self.assertTrue(TestChecker.test(input,expect,404))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 123, in test_func_decl
    self.assertTrue(TestChecker.test(input,expect,411))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_10 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 283, in test_func_decl_10
    self.assertTrue(TestChecker.test(input,expect,421))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_11 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 302, in test_func_decl_11
    self.assertTrue(TestChecker.test(input,expect,422))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_12 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 321, in test_func_decl_12
    self.assertTrue(TestChecker.test(input,expect,423))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_13 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 340, in test_func_decl_13
    self.assertTrue(TestChecker.test(input,expect,424))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_2 (CheckSuite.CheckSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 142, in test_func_decl_2
    self.assertTrue(TestChecker.test(input,expect,413))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_3 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 156, in test_func_decl_3
    self.assertTrue(TestChecker.test(input,expect,414))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_4 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 172, in test_func_decl_4
    self.assertTrue(TestChecker.test(input,expect,415))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_5 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 191, in test_func_decl_5
    self.assertTrue(TestChecker.test(input,expect,416))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_6 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 210, in test_func_decl_6
    self.assertTrue(TestChecker.test(input,expect,417))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_7 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 228, in test_func_decl_7
    self.assertTrue(TestChecker.test(input,expect,418))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_8 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 246, in test_func_decl_8
    self.assertTrue(TestChecker.test(input,expect,419))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_9 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 264, in test_func_decl_9
    self.assertTrue(TestChecker.test(input,expect,420))
AssertionError: False is not true

======================================================================
FAIL: test_init_1 (CheckSuite.CheckSuite)
Simple program: main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 69, in test_init_1
    self.assertTrue(TestChecker.test(input,expect,406))
AssertionError: False is not true

======================================================================
FAIL: test_init_3 (CheckSuite.CheckSuite)
=======
1
1
Tests run  6
Errors  [(<CheckSuite.CheckSuite testMethod=test_init_1>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 68, in test_init_1\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_3>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 88, in test_init_3\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_4>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 98, in test_init_4\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_5>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 108, in test_init_5\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n')]
[]
Test output
 E.EEE.
======================================================================
ERROR: test_init_1 (CheckSuite.CheckSuite)
Simple program: main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 68, in test_init_1
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

======================================================================
ERROR: test_init_3 (CheckSuite.CheckSuite)
>>>>>>> 20e9a7a512675d9d005d1d6aa1bfb762c11c2019
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 88, in test_init_3
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

======================================================================
ERROR: test_init_4 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
<<<<<<< HEAD
  File "./test/CheckSuite.py", line 99, in test_init_4
    self.assertTrue(TestChecker.test(input,expect,409))
AssertionError: False is not true
=======
  File "./test/CheckSuite.py", line 98, in test_init_4
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined
>>>>>>> 20e9a7a512675d9d005d1d6aa1bfb762c11c2019

======================================================================
ERROR: test_init_5 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
<<<<<<< HEAD
  File "./test/CheckSuite.py", line 109, in test_init_5
    self.assertTrue(TestChecker.test(input,expect,410))
AssertionError: False is not true

======================================================================
FAIL: test_no_entry_point (CheckSuite.CheckSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 132, in test_no_entry_point
    self.assertTrue(TestChecker.test(input,expect,412))
AssertionError: False is not true

======================================================================
FAIL: test_redecl_global (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 440, in test_redecl_global
    self.assertTrue(TestChecker.test(input,expect,429))
AssertionError: False is not true

======================================================================
FAIL: test_undecl_var (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 359, in test_undecl_var
    self.assertTrue(TestChecker.test(input,expect,425))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 30 tests in 0.730s

FAILED (failures=25)
=======
  File "./test/CheckSuite.py", line 108, in test_init_5
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.044s

FAILED (errors=4)
>>>>>>> 20e9a7a512675d9d005d1d6aa1bfb762c11c2019

